{{- if .Values.s3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3

    {{- with .Values.s3.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.s3.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "openbalena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: s3

    {{- with .Values.s3.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  {{- with .Values.s3.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
