apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

    {{- with .Values.db.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.db.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "openbalena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db

    {{- with .Values.db.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  {{- with .Values.db.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
