apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry

    {{- with .Values.registry.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.registry.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "openbalena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry

    {{- with .Values.registry.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  {{- with .Values.registry.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
