apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbalena.fullname" . }}-vpn
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: vpn

    {{- with .Values.vpn.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vpn.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "openbalena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vpn

    {{- with .Values.vpn.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
  - name: vpn
    port: 443
    protocol: TCP
  - name: tunnel
    port: 3128
    protocol: TCP
    targetPort: 3128
  {{- with .Values.vpn.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
