# https://github.com/balena-io/open-balena-haproxy
FROM balena/open-balena-haproxy:4.3.18@sha256:0a76ed72a926eb38152b3fe9938ed603be192295bceefee94d13397eddbb6ba1

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
