# https://github.com/balena-io/open-balena-haproxy
FROM balena/open-balena-haproxy:4.3.19@sha256:62689040658d3a716c88efa373e501869c9483ae540e9012042bf2e28facc6e5

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
