apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: s3
  name: s3
  namespace: openbalena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: s3
    spec:
      containers:
      - image: balena/open-balena-s3:${OPENBALENA_S3_VERSION_TAG}
        name: s3
        resources: {}
        volumeMounts:
          - mountPath: /run
            name: cache-volumes
        env:
          - name: CONFD_BACKEND
            value: "ENV"
          - name: S3_MINIO_ACCESS_KEY
            value: "${OPENBALENA_S3_ACCESS_KEY}"
          - name: S3_MINIO_SECRET_KEY
            value: "${OPENBALENA_S3_SECRET_KEY}"
          - name: BUCKETS
            value: "${OPENBALENA_S3_BUCKETS}"

      volumes:
        - name: cache-volumes
          emptyDir:
            medium: Memory
status: {}
