apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: compose-registry
  namespace: openbalena
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
