apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: volume-s3
  namespace: openbalena
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
