# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Hostname of openBalena instance
hostname: "${OPENBALENA_HOST_NAME}" # OPENBALENA_HOST_NAME

# General configurations
config:
  email: "${OPENBALENA_SUPERUSER_EMAIL}" # OPENBALENA_SUPERUSER_EMAIL
  password: "${OPENBALENA_SUPERUSER_PASSWORD}" # OPENBALENA_SUPERUSER_PASSWORD
  production-mode: "${OPENBALENA_PRODUCTION_MODE}" # OPENBALENA_PRODUCTION_MODE
  ssh-authorized-keys: "${OPENBALENA_SSH_AUTHORIZED_KEYS}" # OPENBALENA_SSH_AUTHORIZED_KEYS

  s3:
    bucket: "${OPENBALENA_S3_BUCKETS}" # OPENBALENA_S3_BUCKETS / OPENBALENA_REGISTRY2_S3_BUCKET
    endpoint: "${OPENBALENA_S3_ENDPOINT}" # OPENBALENA_S3_ENDPOINT
    region: "${OPENBALENA_S3_REGION}" # OPENBALENA_S3_REGION
    access-key: "${OPENBALENA_S3_ACCESS_KEY}" # OPENBALENA_S3_ACCESS_KEY
    secret-key: "${OPENBALENA_S3_SECRET_KEY}" # OPENBALENA_S3_SECRET_KEY

# Keys
keys:
  cookie-secret: "${OPENBALENA_COOKIE_SESSION_SECRET}" # OPENBALENA_COOKIE_SESSION_SECRET
  jwt-secret: ${OPENBALENA_JWT_SECRET} # OPENBALENA_JWT_SECRET
  registry-code: ${OPENBALENA_RESINOS_REGISTRY_CODE} # OPENBALENA_RESINOS_REGISTRY_CODE
  service-api-key: "${OPENBALENA_VPN_SERVICE_API_KEY}" # OPENBALENA_VPN_SERVICE_API_KEY
  api-vpn-service-api-key: "${OPENBALENA_API_VPN_SERVICE_API_KEY}" # OPENBALENA_API_VPN_SERVICE_API_KEY
  registry-secret-key: "${OPENBALENA_REGISTRY_SECRET_KEY}" # OPENBALENA_REGISTRY_SECRET_KEY
  token-auth-builder-token: "${OPENBALENA_TOKEN_AUTH_BUILDER_TOKEN}" # OPENBALENA_TOKEN_AUTH_BUILDER_TOKEN
  token-auth-pub: "${OPENBALENA_TOKEN_AUTH_PUB}" # OPENBALENA_TOKEN_AUTH_PUB
  token-auth-key: "${OPENBALENA_TOKEN_AUTH_KEY}" # OPENBALENA_TOKEN_AUTH_KEY
  token-auth-kid: "${OPENBALENA_TOKEN_AUTH_KID}" # OPENBALENA_TOKEN_AUTH_KID

# Certificates
certificates:
  # Root certificates
  root:
    # OPENBALENA_ROOT_CA
    ca: "${OPENBALENA_ROOT_CA}"

    # OPENBALENA_ROOT_CRT
    crt: "${OPENBALENA_ROOT_CRT}"

    # OPENBALENA_ROOT_KEY
    key: "${OPENBALENA_ROOT_KEY}"

  vpn:
    # OPENBALENA_VPN_CA
    ca: "${OPENBALENA_VPN_CA}"

    # OPENBALENA_VPN_CA_CHAIN
    ca-chain: "${OPENBALENA_VPN_CA_CHAIN}"

    # OPENBALENA_VPN_SERVER_CRT
    crt: "${OPENBALENA_VPN_SERVER_CRT}"

    # OPENBALENA_VPN_SERVER_KEY
    server-key: "${OPENBALENA_VPN_SERVER_KEY}"

    # OPENBALENA_VPN_SERVER_DH
    dh: "${OPENBALENA_VPN_SERVER_DH}"
