{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "openbalena.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.http.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.global.hostname }}
    - api.{{ .Values.global.hostname }}
    - registry.{{ .Values.global.hostname }}

    {{- if .Values.s3.enabled }}
    - s3.{{ .Values.global.hostname }}
    {{- end }}
    secretName: {{ include "openbalena.fullname" . }}-tls
  rules:
  - host: api.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-api
            port:
              number: 80
  - host: registry.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-registry
            port:
              number: 80
  {{- if .Values.s3.enabled }}
  - host: s3.{{ .Values.global.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openbalena.fullname" . }}-s3
            port:
              number: 80
  {{- end }}
