version: "2.0"

services:
  balena-mdns-publisher:
    image: balena/balena-mdns-publisher:${OPENBALENA_MDNS_PUBLISHER_VERSION_TAG}
    network_mode: "host"
    cap_add:
        - SYS_RESOURCE
        - SYS_ADMIN
    security_opt:
        - apparmor:unconfined
    tmpfs:
        - /run
        - /sys/fs/cgroup
    restart: always
    # balenaOS - Required for host DBus comms. Not required for standalone Linux
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.supervisor-api: '1'
    environment:
        CONFD_BACKEND: ENV
        # The name of the TLD to use. This *must* match certificates used for the rest of
        # the resin backend (eg. that for BALENA_ROOT_CA if present).
        MDNS_TLD: ${OPENBALENA_HOST_NAME}
        # List of subdomains to advertise. This must include all required hosts.
        MDNS_SUBDOMAINS: '["api", "db", "registry", "s3", "vpn"]'
        # The expectation is the DBus socket to use is always at the following location.
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
        # Selects the interface used for incoming connections from the wider subnet.
        # For NUCs, this is `eno1`. If running natively, pick the appropriate interface.
        # Alternatively, keep the default commented out to autoselect.
        #INTERFACE: "eno1"
