#!/bin/bash -e

usage() {
  echo "usage: $0 USERNAME EMAIL PASSWORD"
}

if [ -z "$1" ]; then
  usage
  exit 1
fi

CMD="$(realpath "$0")"
DIR="$(dirname "${CMD}")"

FIG="${DIR}/compose"

USERNAME="$1"
EMAIL="$2"
PASSWORD="$3"

"${FIG}" exec api /bin/bash -c 'export $(grep -v "^#" config/env | xargs -d "\n"); node index.js create-superuser '${USERNAME}' '${EMAIL}' '${PASSWORD}''
