#!/bin/bash -e

source "${BASH_SOURCE%/*}/_realpath"

CMD="$(realpath "$0")"
DIR="$(dirname "${CMD}")"
BASE_DIR="$(dirname "${DIR}")"
CONFIG_DIR="${BASE_DIR}/config"

NAMESPACE="${NAMESPACE:-default}"
CERT_MANAGER="https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml"

echo_bold() {
  printf "\\033[1m%s\\033[0m\\n" "$@"
}

VERSIONS_FILE="${BASE_DIR}/compose/versions"
if [ ! -f "$VERSIONS_FILE" ]; then
  echo_bold "No service versions defined in ${VERSIONS_FILE}"
  exit 1
fi

SETTINGS_FILE="${CONFIG_DIR}/kubernetes.yaml"
if [[ ! -f "$SETTINGS_FILE" ]]; then
  echo_bold 'No configuration found; please create one first with: ./scripts/quickstart'
  echo_bold 'See README.md for help.'
  exit 1
fi

# Uninstall
if [ "$@" = "uninstall" ]; then
  helm uninstall openbalena --namespace $NAMESPACE
  kubectl delete -f $CERT_MANAGER
  exit 0
fi

install_certmanager () {
  kubectl apply -f $CERT_MANAGER
}

install_openbalena () {
  helm dependency update "${BASE_DIR}/k8s/chart"
  helm upgrade --install openbalena "${BASE_DIR}/k8s/chart" --namespace $NAMESPACE -f "${SETTINGS_FILE}"
}

# Install cert-manager only when using install command
if [ "$@" = "install" ]; then
  install_certmanager
fi

# Always use install_openbalena, because it upgrades as well
install_openbalena
