#!/bin/bash -e

usage() {
  echo "usage: $0 PROJECT_PATH"
  echo
  echo "  PROJECT_PATH  path to the project; can be relative to open-balena root."
  echo
}

if [ -z "$1" ]; then
  usage
  exit 1
fi

CMD="$0"
DIR="$(dirname "${CMD}")"
BASE_DIR="$(dirname "${DIR}")"

PROJECT_PATH="$1"
PROJECT_DIR="$(realpath "${PROJECT_PATH}")"

if [ ! -d "$PROJECT_DIR" ]; then
  echo 'Project path refers to a directory that does not exist.'
  exit 1
fi

if [ ! -f "${PROJECT_DIR}/activate" ]; then
  echo 'Project path refers to a directory that is not a valid project.'
  exit 1
fi

echo -n "${PROJECT_DIR}" >"${BASE_DIR}/.project"
