#!/bin/bash -eu

CMD=$0
DIR=$(dirname "$CMD")
BASE_DIR=$(dirname "$DIR")

PROJECT_NAME=${1:-demo}
HOST_NAME=${2:-openbalena.local}

PROJECT_DIR="$(pwd)/${PROJECT_NAME}"
CERTS_DIR="${PROJECT_DIR}/certs"

usage() {
  echo "usage: $0 [PROJECT_NAME [HOST_NAME]]"
  echo
  echo "  PROJECT_NAME  a name for the deployment, eg. staging. Default is 'demo'"
  echo "  HOST_NAME     the domain name this deployment will run as, eg. example.com. Default is 'openbalena.local'"
  echo
}

echo_bold() {
  printf "\033[1m%s\033[0m\n" "${@}"
}

if [ -d "$PROJECT_DIR" ]; then
  echo 'Project directory already exists. Please remove it or specify another project name.'
  exit 1
fi

echo_bold "==> Creating new project at: $PROJECT_DIR"
mkdir -p "$PROJECT_DIR" "$CERTS_DIR"

echo_bold "==> Generating root CA cert..."
source "${DIR}/gen-root-ca" "${HOST_NAME}" "${CERTS_DIR}"

echo_bold "==> Generating root cert chain for haproxy..."
source "${DIR}/gen-root-cert" "${HOST_NAME}" "${CERTS_DIR}"

echo_bold "==> Generating token auth cert..."
source "${DIR}/gen-token-auth-cert" "${HOST_NAME}" "${CERTS_DIR}"

echo_bold "==> Generating VPN CA, cert and dhparam (this may take a while)..."
source "${DIR}/gen-vpn-certs" "${HOST_NAME}" "${CERTS_DIR}"

echo_bold "==> Setting up environment..."
cat >"${PROJECT_DIR}/activate" <(source "${DIR}/make-env")

echo_bold "==> Adding default compose file..."
cp "${BASE_DIR}/compose/template.yml" "${PROJECT_DIR}/docker-compose.yml"

# FIXME: should be explicitly requested via a flag
echo_bold "==> Patching /etc/hosts..."
"${DIR}/patch-hosts" $HOST_NAME

echo_bold "==> Activating project..."
"${DIR}/select-project" "${PROJECT_DIR}"