apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: openbalena-db-volume
  labels:
    app: openbalena
    component: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ index .Values "deployments" "db" "volume" "storage" }}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: db
  name: openbalena-db
spec:
  replicas: {{ index .Values "deployments" "db" "replicas" }}
  selector:
    matchLabels:
      app: openbalena
      component: db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openbalena
        component: db
    spec:
      containers:
      - image: {{ index .Values "deployments" "db" "image" }}:{{ index .Values "deployments" "db" "version" }}
        name: openbalena-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: openbalena-db-volume
          subPath: postgres
      volumes:
      - name: openbalena-db-volume
        persistentVolumeClaim:
          claimName: openbalena-db-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: db
  name: openbalena-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: openbalena
    component: db
status:
  loadBalancer: {}
