apiVersion: v2
name: openbalena
description: openBalena kubernetes Chart
type: application
version: 3.2.1
appVersion: v3.2.1
keywords:
- balena
- openbalena
maintainers:
- name: bartversluijs
  email: bartv@nexelit.io

dependencies:
- name: haproxy-ingress
  version: 0.13.0-snapshot.1
  alias: haproxy
  repository: "https://haproxy-ingress.github.io/charts"

